// Lab1_sys_mm_interconnect_1.v

// This file was auto-generated from altera_mm_interconnect_hw.tcl.  If you edit it your changes
// will probably be lost.
// 
// Generated using ACDS version 16.1 203

`timescale 1 ps / 1 ps
module Lab1_sys_mm_interconnect_1 (
		input  wire        clk_0_clk_clk,                                //                              clk_0_clk.clk
		input  wire        my_masterB_reset_reset_bridge_in_reset_reset, // my_masterB_reset_reset_bridge_in_reset.reset
		input  wire [31:0] my_masterB_m0_address,                        //                          my_masterB_m0.address
		output wire        my_masterB_m0_waitrequest,                    //                                       .waitrequest
		input  wire        my_masterB_m0_write,                          //                                       .write
		input  wire [31:0] my_masterB_m0_writedata,                      //                                       .writedata
		output wire        ST_ALU_0_s0_write,                            //                            ST_ALU_0_s0.write
		output wire [31:0] ST_ALU_0_s0_writedata,                        //                                       .writedata
		input  wire        ST_ALU_0_s0_waitrequest,                      //                                       .waitrequest
		output wire        ST_ALU_1_s0_write,                            //                            ST_ALU_1_s0.write
		output wire [31:0] ST_ALU_1_s0_writedata,                        //                                       .writedata
		input  wire        ST_ALU_1_s0_waitrequest                       //                                       .waitrequest
	);

	wire          my_masterb_m0_translator_avalon_universal_master_0_waitrequest;   // my_masterB_m0_agent:av_waitrequest -> my_masterB_m0_translator:uav_waitrequest
	wire   [31:0] my_masterb_m0_translator_avalon_universal_master_0_readdata;      // my_masterB_m0_agent:av_readdata -> my_masterB_m0_translator:uav_readdata
	wire          my_masterb_m0_translator_avalon_universal_master_0_debugaccess;   // my_masterB_m0_translator:uav_debugaccess -> my_masterB_m0_agent:av_debugaccess
	wire   [31:0] my_masterb_m0_translator_avalon_universal_master_0_address;       // my_masterB_m0_translator:uav_address -> my_masterB_m0_agent:av_address
	wire          my_masterb_m0_translator_avalon_universal_master_0_read;          // my_masterB_m0_translator:uav_read -> my_masterB_m0_agent:av_read
	wire    [3:0] my_masterb_m0_translator_avalon_universal_master_0_byteenable;    // my_masterB_m0_translator:uav_byteenable -> my_masterB_m0_agent:av_byteenable
	wire          my_masterb_m0_translator_avalon_universal_master_0_readdatavalid; // my_masterB_m0_agent:av_readdatavalid -> my_masterB_m0_translator:uav_readdatavalid
	wire          my_masterb_m0_translator_avalon_universal_master_0_lock;          // my_masterB_m0_translator:uav_lock -> my_masterB_m0_agent:av_lock
	wire          my_masterb_m0_translator_avalon_universal_master_0_write;         // my_masterB_m0_translator:uav_write -> my_masterB_m0_agent:av_write
	wire   [31:0] my_masterb_m0_translator_avalon_universal_master_0_writedata;     // my_masterB_m0_translator:uav_writedata -> my_masterB_m0_agent:av_writedata
	wire    [2:0] my_masterb_m0_translator_avalon_universal_master_0_burstcount;    // my_masterB_m0_translator:uav_burstcount -> my_masterB_m0_agent:av_burstcount
	wire          rsp_mux_src_valid;                                                // rsp_mux:src_valid -> my_masterB_m0_agent:rp_valid
	wire  [101:0] rsp_mux_src_data;                                                 // rsp_mux:src_data -> my_masterB_m0_agent:rp_data
	wire          rsp_mux_src_ready;                                                // my_masterB_m0_agent:rp_ready -> rsp_mux:src_ready
	wire    [1:0] rsp_mux_src_channel;                                              // rsp_mux:src_channel -> my_masterB_m0_agent:rp_channel
	wire          rsp_mux_src_startofpacket;                                        // rsp_mux:src_startofpacket -> my_masterB_m0_agent:rp_startofpacket
	wire          rsp_mux_src_endofpacket;                                          // rsp_mux:src_endofpacket -> my_masterB_m0_agent:rp_endofpacket
	wire   [31:0] st_alu_0_s0_agent_m0_readdata;                                    // ST_ALU_0_s0_translator:uav_readdata -> ST_ALU_0_s0_agent:m0_readdata
	wire          st_alu_0_s0_agent_m0_waitrequest;                                 // ST_ALU_0_s0_translator:uav_waitrequest -> ST_ALU_0_s0_agent:m0_waitrequest
	wire          st_alu_0_s0_agent_m0_debugaccess;                                 // ST_ALU_0_s0_agent:m0_debugaccess -> ST_ALU_0_s0_translator:uav_debugaccess
	wire   [31:0] st_alu_0_s0_agent_m0_address;                                     // ST_ALU_0_s0_agent:m0_address -> ST_ALU_0_s0_translator:uav_address
	wire    [3:0] st_alu_0_s0_agent_m0_byteenable;                                  // ST_ALU_0_s0_agent:m0_byteenable -> ST_ALU_0_s0_translator:uav_byteenable
	wire          st_alu_0_s0_agent_m0_read;                                        // ST_ALU_0_s0_agent:m0_read -> ST_ALU_0_s0_translator:uav_read
	wire          st_alu_0_s0_agent_m0_readdatavalid;                               // ST_ALU_0_s0_translator:uav_readdatavalid -> ST_ALU_0_s0_agent:m0_readdatavalid
	wire          st_alu_0_s0_agent_m0_lock;                                        // ST_ALU_0_s0_agent:m0_lock -> ST_ALU_0_s0_translator:uav_lock
	wire   [31:0] st_alu_0_s0_agent_m0_writedata;                                   // ST_ALU_0_s0_agent:m0_writedata -> ST_ALU_0_s0_translator:uav_writedata
	wire          st_alu_0_s0_agent_m0_write;                                       // ST_ALU_0_s0_agent:m0_write -> ST_ALU_0_s0_translator:uav_write
	wire    [2:0] st_alu_0_s0_agent_m0_burstcount;                                  // ST_ALU_0_s0_agent:m0_burstcount -> ST_ALU_0_s0_translator:uav_burstcount
	wire          st_alu_0_s0_agent_rf_source_valid;                                // ST_ALU_0_s0_agent:rf_source_valid -> ST_ALU_0_s0_agent_rsp_fifo:in_valid
	wire  [102:0] st_alu_0_s0_agent_rf_source_data;                                 // ST_ALU_0_s0_agent:rf_source_data -> ST_ALU_0_s0_agent_rsp_fifo:in_data
	wire          st_alu_0_s0_agent_rf_source_ready;                                // ST_ALU_0_s0_agent_rsp_fifo:in_ready -> ST_ALU_0_s0_agent:rf_source_ready
	wire          st_alu_0_s0_agent_rf_source_startofpacket;                        // ST_ALU_0_s0_agent:rf_source_startofpacket -> ST_ALU_0_s0_agent_rsp_fifo:in_startofpacket
	wire          st_alu_0_s0_agent_rf_source_endofpacket;                          // ST_ALU_0_s0_agent:rf_source_endofpacket -> ST_ALU_0_s0_agent_rsp_fifo:in_endofpacket
	wire          st_alu_0_s0_agent_rsp_fifo_out_valid;                             // ST_ALU_0_s0_agent_rsp_fifo:out_valid -> ST_ALU_0_s0_agent:rf_sink_valid
	wire  [102:0] st_alu_0_s0_agent_rsp_fifo_out_data;                              // ST_ALU_0_s0_agent_rsp_fifo:out_data -> ST_ALU_0_s0_agent:rf_sink_data
	wire          st_alu_0_s0_agent_rsp_fifo_out_ready;                             // ST_ALU_0_s0_agent:rf_sink_ready -> ST_ALU_0_s0_agent_rsp_fifo:out_ready
	wire          st_alu_0_s0_agent_rsp_fifo_out_startofpacket;                     // ST_ALU_0_s0_agent_rsp_fifo:out_startofpacket -> ST_ALU_0_s0_agent:rf_sink_startofpacket
	wire          st_alu_0_s0_agent_rsp_fifo_out_endofpacket;                       // ST_ALU_0_s0_agent_rsp_fifo:out_endofpacket -> ST_ALU_0_s0_agent:rf_sink_endofpacket
	wire          cmd_mux_src_valid;                                                // cmd_mux:src_valid -> ST_ALU_0_s0_agent:cp_valid
	wire  [101:0] cmd_mux_src_data;                                                 // cmd_mux:src_data -> ST_ALU_0_s0_agent:cp_data
	wire          cmd_mux_src_ready;                                                // ST_ALU_0_s0_agent:cp_ready -> cmd_mux:src_ready
	wire    [1:0] cmd_mux_src_channel;                                              // cmd_mux:src_channel -> ST_ALU_0_s0_agent:cp_channel
	wire          cmd_mux_src_startofpacket;                                        // cmd_mux:src_startofpacket -> ST_ALU_0_s0_agent:cp_startofpacket
	wire          cmd_mux_src_endofpacket;                                          // cmd_mux:src_endofpacket -> ST_ALU_0_s0_agent:cp_endofpacket
	wire   [31:0] st_alu_1_s0_agent_m0_readdata;                                    // ST_ALU_1_s0_translator:uav_readdata -> ST_ALU_1_s0_agent:m0_readdata
	wire          st_alu_1_s0_agent_m0_waitrequest;                                 // ST_ALU_1_s0_translator:uav_waitrequest -> ST_ALU_1_s0_agent:m0_waitrequest
	wire          st_alu_1_s0_agent_m0_debugaccess;                                 // ST_ALU_1_s0_agent:m0_debugaccess -> ST_ALU_1_s0_translator:uav_debugaccess
	wire   [31:0] st_alu_1_s0_agent_m0_address;                                     // ST_ALU_1_s0_agent:m0_address -> ST_ALU_1_s0_translator:uav_address
	wire    [3:0] st_alu_1_s0_agent_m0_byteenable;                                  // ST_ALU_1_s0_agent:m0_byteenable -> ST_ALU_1_s0_translator:uav_byteenable
	wire          st_alu_1_s0_agent_m0_read;                                        // ST_ALU_1_s0_agent:m0_read -> ST_ALU_1_s0_translator:uav_read
	wire          st_alu_1_s0_agent_m0_readdatavalid;                               // ST_ALU_1_s0_translator:uav_readdatavalid -> ST_ALU_1_s0_agent:m0_readdatavalid
	wire          st_alu_1_s0_agent_m0_lock;                                        // ST_ALU_1_s0_agent:m0_lock -> ST_ALU_1_s0_translator:uav_lock
	wire   [31:0] st_alu_1_s0_agent_m0_writedata;                                   // ST_ALU_1_s0_agent:m0_writedata -> ST_ALU_1_s0_translator:uav_writedata
	wire          st_alu_1_s0_agent_m0_write;                                       // ST_ALU_1_s0_agent:m0_write -> ST_ALU_1_s0_translator:uav_write
	wire    [2:0] st_alu_1_s0_agent_m0_burstcount;                                  // ST_ALU_1_s0_agent:m0_burstcount -> ST_ALU_1_s0_translator:uav_burstcount
	wire          st_alu_1_s0_agent_rf_source_valid;                                // ST_ALU_1_s0_agent:rf_source_valid -> ST_ALU_1_s0_agent_rsp_fifo:in_valid
	wire  [102:0] st_alu_1_s0_agent_rf_source_data;                                 // ST_ALU_1_s0_agent:rf_source_data -> ST_ALU_1_s0_agent_rsp_fifo:in_data
	wire          st_alu_1_s0_agent_rf_source_ready;                                // ST_ALU_1_s0_agent_rsp_fifo:in_ready -> ST_ALU_1_s0_agent:rf_source_ready
	wire          st_alu_1_s0_agent_rf_source_startofpacket;                        // ST_ALU_1_s0_agent:rf_source_startofpacket -> ST_ALU_1_s0_agent_rsp_fifo:in_startofpacket
	wire          st_alu_1_s0_agent_rf_source_endofpacket;                          // ST_ALU_1_s0_agent:rf_source_endofpacket -> ST_ALU_1_s0_agent_rsp_fifo:in_endofpacket
	wire          st_alu_1_s0_agent_rsp_fifo_out_valid;                             // ST_ALU_1_s0_agent_rsp_fifo:out_valid -> ST_ALU_1_s0_agent:rf_sink_valid
	wire  [102:0] st_alu_1_s0_agent_rsp_fifo_out_data;                              // ST_ALU_1_s0_agent_rsp_fifo:out_data -> ST_ALU_1_s0_agent:rf_sink_data
	wire          st_alu_1_s0_agent_rsp_fifo_out_ready;                             // ST_ALU_1_s0_agent:rf_sink_ready -> ST_ALU_1_s0_agent_rsp_fifo:out_ready
	wire          st_alu_1_s0_agent_rsp_fifo_out_startofpacket;                     // ST_ALU_1_s0_agent_rsp_fifo:out_startofpacket -> ST_ALU_1_s0_agent:rf_sink_startofpacket
	wire          st_alu_1_s0_agent_rsp_fifo_out_endofpacket;                       // ST_ALU_1_s0_agent_rsp_fifo:out_endofpacket -> ST_ALU_1_s0_agent:rf_sink_endofpacket
	wire          cmd_mux_001_src_valid;                                            // cmd_mux_001:src_valid -> ST_ALU_1_s0_agent:cp_valid
	wire  [101:0] cmd_mux_001_src_data;                                             // cmd_mux_001:src_data -> ST_ALU_1_s0_agent:cp_data
	wire          cmd_mux_001_src_ready;                                            // ST_ALU_1_s0_agent:cp_ready -> cmd_mux_001:src_ready
	wire    [1:0] cmd_mux_001_src_channel;                                          // cmd_mux_001:src_channel -> ST_ALU_1_s0_agent:cp_channel
	wire          cmd_mux_001_src_startofpacket;                                    // cmd_mux_001:src_startofpacket -> ST_ALU_1_s0_agent:cp_startofpacket
	wire          cmd_mux_001_src_endofpacket;                                      // cmd_mux_001:src_endofpacket -> ST_ALU_1_s0_agent:cp_endofpacket
	wire          my_masterb_m0_agent_cp_valid;                                     // my_masterB_m0_agent:cp_valid -> router:sink_valid
	wire  [101:0] my_masterb_m0_agent_cp_data;                                      // my_masterB_m0_agent:cp_data -> router:sink_data
	wire          my_masterb_m0_agent_cp_ready;                                     // router:sink_ready -> my_masterB_m0_agent:cp_ready
	wire          my_masterb_m0_agent_cp_startofpacket;                             // my_masterB_m0_agent:cp_startofpacket -> router:sink_startofpacket
	wire          my_masterb_m0_agent_cp_endofpacket;                               // my_masterB_m0_agent:cp_endofpacket -> router:sink_endofpacket
	wire          router_src_valid;                                                 // router:src_valid -> cmd_demux:sink_valid
	wire  [101:0] router_src_data;                                                  // router:src_data -> cmd_demux:sink_data
	wire          router_src_ready;                                                 // cmd_demux:sink_ready -> router:src_ready
	wire    [1:0] router_src_channel;                                               // router:src_channel -> cmd_demux:sink_channel
	wire          router_src_startofpacket;                                         // router:src_startofpacket -> cmd_demux:sink_startofpacket
	wire          router_src_endofpacket;                                           // router:src_endofpacket -> cmd_demux:sink_endofpacket
	wire          st_alu_0_s0_agent_rp_valid;                                       // ST_ALU_0_s0_agent:rp_valid -> router_001:sink_valid
	wire  [101:0] st_alu_0_s0_agent_rp_data;                                        // ST_ALU_0_s0_agent:rp_data -> router_001:sink_data
	wire          st_alu_0_s0_agent_rp_ready;                                       // router_001:sink_ready -> ST_ALU_0_s0_agent:rp_ready
	wire          st_alu_0_s0_agent_rp_startofpacket;                               // ST_ALU_0_s0_agent:rp_startofpacket -> router_001:sink_startofpacket
	wire          st_alu_0_s0_agent_rp_endofpacket;                                 // ST_ALU_0_s0_agent:rp_endofpacket -> router_001:sink_endofpacket
	wire          router_001_src_valid;                                             // router_001:src_valid -> rsp_demux:sink_valid
	wire  [101:0] router_001_src_data;                                              // router_001:src_data -> rsp_demux:sink_data
	wire          router_001_src_ready;                                             // rsp_demux:sink_ready -> router_001:src_ready
	wire    [1:0] router_001_src_channel;                                           // router_001:src_channel -> rsp_demux:sink_channel
	wire          router_001_src_startofpacket;                                     // router_001:src_startofpacket -> rsp_demux:sink_startofpacket
	wire          router_001_src_endofpacket;                                       // router_001:src_endofpacket -> rsp_demux:sink_endofpacket
	wire          st_alu_1_s0_agent_rp_valid;                                       // ST_ALU_1_s0_agent:rp_valid -> router_002:sink_valid
	wire  [101:0] st_alu_1_s0_agent_rp_data;                                        // ST_ALU_1_s0_agent:rp_data -> router_002:sink_data
	wire          st_alu_1_s0_agent_rp_ready;                                       // router_002:sink_ready -> ST_ALU_1_s0_agent:rp_ready
	wire          st_alu_1_s0_agent_rp_startofpacket;                               // ST_ALU_1_s0_agent:rp_startofpacket -> router_002:sink_startofpacket
	wire          st_alu_1_s0_agent_rp_endofpacket;                                 // ST_ALU_1_s0_agent:rp_endofpacket -> router_002:sink_endofpacket
	wire          router_002_src_valid;                                             // router_002:src_valid -> rsp_demux_001:sink_valid
	wire  [101:0] router_002_src_data;                                              // router_002:src_data -> rsp_demux_001:sink_data
	wire          router_002_src_ready;                                             // rsp_demux_001:sink_ready -> router_002:src_ready
	wire    [1:0] router_002_src_channel;                                           // router_002:src_channel -> rsp_demux_001:sink_channel
	wire          router_002_src_startofpacket;                                     // router_002:src_startofpacket -> rsp_demux_001:sink_startofpacket
	wire          router_002_src_endofpacket;                                       // router_002:src_endofpacket -> rsp_demux_001:sink_endofpacket
	wire          cmd_demux_src0_valid;                                             // cmd_demux:src0_valid -> cmd_mux:sink0_valid
	wire  [101:0] cmd_demux_src0_data;                                              // cmd_demux:src0_data -> cmd_mux:sink0_data
	wire          cmd_demux_src0_ready;                                             // cmd_mux:sink0_ready -> cmd_demux:src0_ready
	wire    [1:0] cmd_demux_src0_channel;                                           // cmd_demux:src0_channel -> cmd_mux:sink0_channel
	wire          cmd_demux_src0_startofpacket;                                     // cmd_demux:src0_startofpacket -> cmd_mux:sink0_startofpacket
	wire          cmd_demux_src0_endofpacket;                                       // cmd_demux:src0_endofpacket -> cmd_mux:sink0_endofpacket
	wire          cmd_demux_src1_valid;                                             // cmd_demux:src1_valid -> cmd_mux_001:sink0_valid
	wire  [101:0] cmd_demux_src1_data;                                              // cmd_demux:src1_data -> cmd_mux_001:sink0_data
	wire          cmd_demux_src1_ready;                                             // cmd_mux_001:sink0_ready -> cmd_demux:src1_ready
	wire    [1:0] cmd_demux_src1_channel;                                           // cmd_demux:src1_channel -> cmd_mux_001:sink0_channel
	wire          cmd_demux_src1_startofpacket;                                     // cmd_demux:src1_startofpacket -> cmd_mux_001:sink0_startofpacket
	wire          cmd_demux_src1_endofpacket;                                       // cmd_demux:src1_endofpacket -> cmd_mux_001:sink0_endofpacket
	wire          rsp_demux_src0_valid;                                             // rsp_demux:src0_valid -> rsp_mux:sink0_valid
	wire  [101:0] rsp_demux_src0_data;                                              // rsp_demux:src0_data -> rsp_mux:sink0_data
	wire          rsp_demux_src0_ready;                                             // rsp_mux:sink0_ready -> rsp_demux:src0_ready
	wire    [1:0] rsp_demux_src0_channel;                                           // rsp_demux:src0_channel -> rsp_mux:sink0_channel
	wire          rsp_demux_src0_startofpacket;                                     // rsp_demux:src0_startofpacket -> rsp_mux:sink0_startofpacket
	wire          rsp_demux_src0_endofpacket;                                       // rsp_demux:src0_endofpacket -> rsp_mux:sink0_endofpacket
	wire          rsp_demux_001_src0_valid;                                         // rsp_demux_001:src0_valid -> rsp_mux:sink1_valid
	wire  [101:0] rsp_demux_001_src0_data;                                          // rsp_demux_001:src0_data -> rsp_mux:sink1_data
	wire          rsp_demux_001_src0_ready;                                         // rsp_mux:sink1_ready -> rsp_demux_001:src0_ready
	wire    [1:0] rsp_demux_001_src0_channel;                                       // rsp_demux_001:src0_channel -> rsp_mux:sink1_channel
	wire          rsp_demux_001_src0_startofpacket;                                 // rsp_demux_001:src0_startofpacket -> rsp_mux:sink1_startofpacket
	wire          rsp_demux_001_src0_endofpacket;                                   // rsp_demux_001:src0_endofpacket -> rsp_mux:sink1_endofpacket
	wire          st_alu_0_s0_agent_rdata_fifo_src_valid;                           // ST_ALU_0_s0_agent:rdata_fifo_src_valid -> avalon_st_adapter:in_0_valid
	wire   [33:0] st_alu_0_s0_agent_rdata_fifo_src_data;                            // ST_ALU_0_s0_agent:rdata_fifo_src_data -> avalon_st_adapter:in_0_data
	wire          st_alu_0_s0_agent_rdata_fifo_src_ready;                           // avalon_st_adapter:in_0_ready -> ST_ALU_0_s0_agent:rdata_fifo_src_ready
	wire          avalon_st_adapter_out_0_valid;                                    // avalon_st_adapter:out_0_valid -> ST_ALU_0_s0_agent:rdata_fifo_sink_valid
	wire   [33:0] avalon_st_adapter_out_0_data;                                     // avalon_st_adapter:out_0_data -> ST_ALU_0_s0_agent:rdata_fifo_sink_data
	wire          avalon_st_adapter_out_0_ready;                                    // ST_ALU_0_s0_agent:rdata_fifo_sink_ready -> avalon_st_adapter:out_0_ready
	wire    [0:0] avalon_st_adapter_out_0_error;                                    // avalon_st_adapter:out_0_error -> ST_ALU_0_s0_agent:rdata_fifo_sink_error
	wire          st_alu_1_s0_agent_rdata_fifo_src_valid;                           // ST_ALU_1_s0_agent:rdata_fifo_src_valid -> avalon_st_adapter_001:in_0_valid
	wire   [33:0] st_alu_1_s0_agent_rdata_fifo_src_data;                            // ST_ALU_1_s0_agent:rdata_fifo_src_data -> avalon_st_adapter_001:in_0_data
	wire          st_alu_1_s0_agent_rdata_fifo_src_ready;                           // avalon_st_adapter_001:in_0_ready -> ST_ALU_1_s0_agent:rdata_fifo_src_ready
	wire          avalon_st_adapter_001_out_0_valid;                                // avalon_st_adapter_001:out_0_valid -> ST_ALU_1_s0_agent:rdata_fifo_sink_valid
	wire   [33:0] avalon_st_adapter_001_out_0_data;                                 // avalon_st_adapter_001:out_0_data -> ST_ALU_1_s0_agent:rdata_fifo_sink_data
	wire          avalon_st_adapter_001_out_0_ready;                                // ST_ALU_1_s0_agent:rdata_fifo_sink_ready -> avalon_st_adapter_001:out_0_ready
	wire    [0:0] avalon_st_adapter_001_out_0_error;                                // avalon_st_adapter_001:out_0_error -> ST_ALU_1_s0_agent:rdata_fifo_sink_error

	altera_merlin_master_translator #(
		.AV_ADDRESS_W                (32),
		.AV_DATA_W                   (32),
		.AV_BURSTCOUNT_W             (1),
		.AV_BYTEENABLE_W             (4),
		.UAV_ADDRESS_W               (32),
		.UAV_BURSTCOUNT_W            (3),
		.USE_READ                    (0),
		.USE_WRITE                   (1),
		.USE_BEGINBURSTTRANSFER      (0),
		.USE_BEGINTRANSFER           (0),
		.USE_CHIPSELECT              (0),
		.USE_BURSTCOUNT              (0),
		.USE_READDATAVALID           (0),
		.USE_WAITREQUEST             (1),
		.USE_READRESPONSE            (0),
		.USE_WRITERESPONSE           (0),
		.AV_SYMBOLS_PER_WORD         (4),
		.AV_ADDRESS_SYMBOLS          (1),
		.AV_BURSTCOUNT_SYMBOLS       (0),
		.AV_CONSTANT_BURST_BEHAVIOR  (0),
		.UAV_CONSTANT_BURST_BEHAVIOR (0),
		.AV_LINEWRAPBURSTS           (0),
		.AV_REGISTERINCOMINGSIGNALS  (0)
	) my_masterb_m0_translator (
		.clk                    (clk_0_clk_clk),                                                    //                       clk.clk
		.reset                  (my_masterB_reset_reset_bridge_in_reset_reset),                     //                     reset.reset
		.uav_address            (my_masterb_m0_translator_avalon_universal_master_0_address),       // avalon_universal_master_0.address
		.uav_burstcount         (my_masterb_m0_translator_avalon_universal_master_0_burstcount),    //                          .burstcount
		.uav_read               (my_masterb_m0_translator_avalon_universal_master_0_read),          //                          .read
		.uav_write              (my_masterb_m0_translator_avalon_universal_master_0_write),         //                          .write
		.uav_waitrequest        (my_masterb_m0_translator_avalon_universal_master_0_waitrequest),   //                          .waitrequest
		.uav_readdatavalid      (my_masterb_m0_translator_avalon_universal_master_0_readdatavalid), //                          .readdatavalid
		.uav_byteenable         (my_masterb_m0_translator_avalon_universal_master_0_byteenable),    //                          .byteenable
		.uav_readdata           (my_masterb_m0_translator_avalon_universal_master_0_readdata),      //                          .readdata
		.uav_writedata          (my_masterb_m0_translator_avalon_universal_master_0_writedata),     //                          .writedata
		.uav_lock               (my_masterb_m0_translator_avalon_universal_master_0_lock),          //                          .lock
		.uav_debugaccess        (my_masterb_m0_translator_avalon_universal_master_0_debugaccess),   //                          .debugaccess
		.av_address             (my_masterB_m0_address),                                            //      avalon_anti_master_0.address
		.av_waitrequest         (my_masterB_m0_waitrequest),                                        //                          .waitrequest
		.av_write               (my_masterB_m0_write),                                              //                          .write
		.av_writedata           (my_masterB_m0_writedata),                                          //                          .writedata
		.av_burstcount          (1'b1),                                                             //               (terminated)
		.av_byteenable          (4'b1111),                                                          //               (terminated)
		.av_beginbursttransfer  (1'b0),                                                             //               (terminated)
		.av_begintransfer       (1'b0),                                                             //               (terminated)
		.av_chipselect          (1'b0),                                                             //               (terminated)
		.av_read                (1'b0),                                                             //               (terminated)
		.av_readdata            (),                                                                 //               (terminated)
		.av_readdatavalid       (),                                                                 //               (terminated)
		.av_lock                (1'b0),                                                             //               (terminated)
		.av_debugaccess         (1'b0),                                                             //               (terminated)
		.uav_clken              (),                                                                 //               (terminated)
		.av_clken               (1'b1),                                                             //               (terminated)
		.uav_response           (2'b00),                                                            //               (terminated)
		.av_response            (),                                                                 //               (terminated)
		.uav_writeresponsevalid (1'b0),                                                             //               (terminated)
		.av_writeresponsevalid  ()                                                                  //               (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (1),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) st_alu_0_s0_translator (
		.clk                    (clk_0_clk_clk),                                //                      clk.clk
		.reset                  (my_masterB_reset_reset_bridge_in_reset_reset), //                    reset.reset
		.uav_address            (st_alu_0_s0_agent_m0_address),                 // avalon_universal_slave_0.address
		.uav_burstcount         (st_alu_0_s0_agent_m0_burstcount),              //                         .burstcount
		.uav_read               (st_alu_0_s0_agent_m0_read),                    //                         .read
		.uav_write              (st_alu_0_s0_agent_m0_write),                   //                         .write
		.uav_waitrequest        (st_alu_0_s0_agent_m0_waitrequest),             //                         .waitrequest
		.uav_readdatavalid      (st_alu_0_s0_agent_m0_readdatavalid),           //                         .readdatavalid
		.uav_byteenable         (st_alu_0_s0_agent_m0_byteenable),              //                         .byteenable
		.uav_readdata           (st_alu_0_s0_agent_m0_readdata),                //                         .readdata
		.uav_writedata          (st_alu_0_s0_agent_m0_writedata),               //                         .writedata
		.uav_lock               (st_alu_0_s0_agent_m0_lock),                    //                         .lock
		.uav_debugaccess        (st_alu_0_s0_agent_m0_debugaccess),             //                         .debugaccess
		.av_write               (ST_ALU_0_s0_write),                            //      avalon_anti_slave_0.write
		.av_writedata           (ST_ALU_0_s0_writedata),                        //                         .writedata
		.av_waitrequest         (ST_ALU_0_s0_waitrequest),                      //                         .waitrequest
		.av_address             (),                                             //              (terminated)
		.av_read                (),                                             //              (terminated)
		.av_readdata            (32'b11011110101011011101111010101101),         //              (terminated)
		.av_begintransfer       (),                                             //              (terminated)
		.av_beginbursttransfer  (),                                             //              (terminated)
		.av_burstcount          (),                                             //              (terminated)
		.av_byteenable          (),                                             //              (terminated)
		.av_readdatavalid       (1'b0),                                         //              (terminated)
		.av_writebyteenable     (),                                             //              (terminated)
		.av_lock                (),                                             //              (terminated)
		.av_chipselect          (),                                             //              (terminated)
		.av_clken               (),                                             //              (terminated)
		.uav_clken              (1'b0),                                         //              (terminated)
		.av_debugaccess         (),                                             //              (terminated)
		.av_outputenable        (),                                             //              (terminated)
		.uav_response           (),                                             //              (terminated)
		.av_response            (2'b00),                                        //              (terminated)
		.uav_writeresponsevalid (),                                             //              (terminated)
		.av_writeresponsevalid  (1'b0)                                          //              (terminated)
	);

	altera_merlin_slave_translator #(
		.AV_ADDRESS_W                   (1),
		.AV_DATA_W                      (32),
		.UAV_DATA_W                     (32),
		.AV_BURSTCOUNT_W                (1),
		.AV_BYTEENABLE_W                (4),
		.UAV_BYTEENABLE_W               (4),
		.UAV_ADDRESS_W                  (32),
		.UAV_BURSTCOUNT_W               (3),
		.AV_READLATENCY                 (0),
		.USE_READDATAVALID              (0),
		.USE_WAITREQUEST                (1),
		.USE_UAV_CLKEN                  (0),
		.USE_READRESPONSE               (0),
		.USE_WRITERESPONSE              (0),
		.AV_SYMBOLS_PER_WORD            (4),
		.AV_ADDRESS_SYMBOLS             (0),
		.AV_BURSTCOUNT_SYMBOLS          (0),
		.AV_CONSTANT_BURST_BEHAVIOR     (0),
		.UAV_CONSTANT_BURST_BEHAVIOR    (0),
		.AV_REQUIRE_UNALIGNED_ADDRESSES (0),
		.CHIPSELECT_THROUGH_READLATENCY (0),
		.AV_READ_WAIT_CYCLES            (1),
		.AV_WRITE_WAIT_CYCLES           (0),
		.AV_SETUP_WAIT_CYCLES           (0),
		.AV_DATA_HOLD_CYCLES            (0)
	) st_alu_1_s0_translator (
		.clk                    (clk_0_clk_clk),                                //                      clk.clk
		.reset                  (my_masterB_reset_reset_bridge_in_reset_reset), //                    reset.reset
		.uav_address            (st_alu_1_s0_agent_m0_address),                 // avalon_universal_slave_0.address
		.uav_burstcount         (st_alu_1_s0_agent_m0_burstcount),              //                         .burstcount
		.uav_read               (st_alu_1_s0_agent_m0_read),                    //                         .read
		.uav_write              (st_alu_1_s0_agent_m0_write),                   //                         .write
		.uav_waitrequest        (st_alu_1_s0_agent_m0_waitrequest),             //                         .waitrequest
		.uav_readdatavalid      (st_alu_1_s0_agent_m0_readdatavalid),           //                         .readdatavalid
		.uav_byteenable         (st_alu_1_s0_agent_m0_byteenable),              //                         .byteenable
		.uav_readdata           (st_alu_1_s0_agent_m0_readdata),                //                         .readdata
		.uav_writedata          (st_alu_1_s0_agent_m0_writedata),               //                         .writedata
		.uav_lock               (st_alu_1_s0_agent_m0_lock),                    //                         .lock
		.uav_debugaccess        (st_alu_1_s0_agent_m0_debugaccess),             //                         .debugaccess
		.av_write               (ST_ALU_1_s0_write),                            //      avalon_anti_slave_0.write
		.av_writedata           (ST_ALU_1_s0_writedata),                        //                         .writedata
		.av_waitrequest         (ST_ALU_1_s0_waitrequest),                      //                         .waitrequest
		.av_address             (),                                             //              (terminated)
		.av_read                (),                                             //              (terminated)
		.av_readdata            (32'b11011110101011011101111010101101),         //              (terminated)
		.av_begintransfer       (),                                             //              (terminated)
		.av_beginbursttransfer  (),                                             //              (terminated)
		.av_burstcount          (),                                             //              (terminated)
		.av_byteenable          (),                                             //              (terminated)
		.av_readdatavalid       (1'b0),                                         //              (terminated)
		.av_writebyteenable     (),                                             //              (terminated)
		.av_lock                (),                                             //              (terminated)
		.av_chipselect          (),                                             //              (terminated)
		.av_clken               (),                                             //              (terminated)
		.uav_clken              (1'b0),                                         //              (terminated)
		.av_debugaccess         (),                                             //              (terminated)
		.av_outputenable        (),                                             //              (terminated)
		.uav_response           (),                                             //              (terminated)
		.av_response            (2'b00),                                        //              (terminated)
		.uav_writeresponsevalid (),                                             //              (terminated)
		.av_writeresponsevalid  (1'b0)                                          //              (terminated)
	);

	altera_merlin_master_agent #(
		.PKT_ORI_BURST_SIZE_H      (101),
		.PKT_ORI_BURST_SIZE_L      (99),
		.PKT_RESPONSE_STATUS_H     (98),
		.PKT_RESPONSE_STATUS_L     (97),
		.PKT_QOS_H                 (86),
		.PKT_QOS_L                 (86),
		.PKT_DATA_SIDEBAND_H       (84),
		.PKT_DATA_SIDEBAND_L       (84),
		.PKT_ADDR_SIDEBAND_H       (83),
		.PKT_ADDR_SIDEBAND_L       (83),
		.PKT_BURST_TYPE_H          (82),
		.PKT_BURST_TYPE_L          (81),
		.PKT_CACHE_H               (96),
		.PKT_CACHE_L               (93),
		.PKT_THREAD_ID_H           (89),
		.PKT_THREAD_ID_L           (89),
		.PKT_BURST_SIZE_H          (80),
		.PKT_BURST_SIZE_L          (78),
		.PKT_TRANS_EXCLUSIVE       (73),
		.PKT_TRANS_LOCK            (72),
		.PKT_BEGIN_BURST           (85),
		.PKT_PROTECTION_H          (92),
		.PKT_PROTECTION_L          (90),
		.PKT_BURSTWRAP_H           (77),
		.PKT_BURSTWRAP_L           (77),
		.PKT_BYTE_CNT_H            (76),
		.PKT_BYTE_CNT_L            (74),
		.PKT_ADDR_H                (67),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (68),
		.PKT_TRANS_POSTED          (69),
		.PKT_TRANS_WRITE           (70),
		.PKT_TRANS_READ            (71),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (87),
		.PKT_SRC_ID_L              (87),
		.PKT_DEST_ID_H             (88),
		.PKT_DEST_ID_L             (88),
		.ST_DATA_W                 (102),
		.ST_CHANNEL_W              (2),
		.AV_BURSTCOUNT_W           (3),
		.SUPPRESS_0_BYTEEN_RSP     (0),
		.ID                        (0),
		.BURSTWRAP_VALUE           (1),
		.CACHE_VALUE               (0),
		.SECURE_ACCESS_BIT         (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0)
	) my_masterb_m0_agent (
		.clk                   (clk_0_clk_clk),                                                    //       clk.clk
		.reset                 (my_masterB_reset_reset_bridge_in_reset_reset),                     // clk_reset.reset
		.av_address            (my_masterb_m0_translator_avalon_universal_master_0_address),       //        av.address
		.av_write              (my_masterb_m0_translator_avalon_universal_master_0_write),         //          .write
		.av_read               (my_masterb_m0_translator_avalon_universal_master_0_read),          //          .read
		.av_writedata          (my_masterb_m0_translator_avalon_universal_master_0_writedata),     //          .writedata
		.av_readdata           (my_masterb_m0_translator_avalon_universal_master_0_readdata),      //          .readdata
		.av_waitrequest        (my_masterb_m0_translator_avalon_universal_master_0_waitrequest),   //          .waitrequest
		.av_readdatavalid      (my_masterb_m0_translator_avalon_universal_master_0_readdatavalid), //          .readdatavalid
		.av_byteenable         (my_masterb_m0_translator_avalon_universal_master_0_byteenable),    //          .byteenable
		.av_burstcount         (my_masterb_m0_translator_avalon_universal_master_0_burstcount),    //          .burstcount
		.av_debugaccess        (my_masterb_m0_translator_avalon_universal_master_0_debugaccess),   //          .debugaccess
		.av_lock               (my_masterb_m0_translator_avalon_universal_master_0_lock),          //          .lock
		.cp_valid              (my_masterb_m0_agent_cp_valid),                                     //        cp.valid
		.cp_data               (my_masterb_m0_agent_cp_data),                                      //          .data
		.cp_startofpacket      (my_masterb_m0_agent_cp_startofpacket),                             //          .startofpacket
		.cp_endofpacket        (my_masterb_m0_agent_cp_endofpacket),                               //          .endofpacket
		.cp_ready              (my_masterb_m0_agent_cp_ready),                                     //          .ready
		.rp_valid              (rsp_mux_src_valid),                                                //        rp.valid
		.rp_data               (rsp_mux_src_data),                                                 //          .data
		.rp_channel            (rsp_mux_src_channel),                                              //          .channel
		.rp_startofpacket      (rsp_mux_src_startofpacket),                                        //          .startofpacket
		.rp_endofpacket        (rsp_mux_src_endofpacket),                                          //          .endofpacket
		.rp_ready              (rsp_mux_src_ready),                                                //          .ready
		.av_response           (),                                                                 // (terminated)
		.av_writeresponsevalid ()                                                                  // (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_ORI_BURST_SIZE_H      (101),
		.PKT_ORI_BURST_SIZE_L      (99),
		.PKT_RESPONSE_STATUS_H     (98),
		.PKT_RESPONSE_STATUS_L     (97),
		.PKT_BURST_SIZE_H          (80),
		.PKT_BURST_SIZE_L          (78),
		.PKT_TRANS_LOCK            (72),
		.PKT_BEGIN_BURST           (85),
		.PKT_PROTECTION_H          (92),
		.PKT_PROTECTION_L          (90),
		.PKT_BURSTWRAP_H           (77),
		.PKT_BURSTWRAP_L           (77),
		.PKT_BYTE_CNT_H            (76),
		.PKT_BYTE_CNT_L            (74),
		.PKT_ADDR_H                (67),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (68),
		.PKT_TRANS_POSTED          (69),
		.PKT_TRANS_WRITE           (70),
		.PKT_TRANS_READ            (71),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (87),
		.PKT_SRC_ID_L              (87),
		.PKT_DEST_ID_H             (88),
		.PKT_DEST_ID_L             (88),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (2),
		.ST_DATA_W                 (102),
		.AVS_BURSTCOUNT_W          (3),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0)
	) st_alu_0_s0_agent (
		.clk                     (clk_0_clk_clk),                                //             clk.clk
		.reset                   (my_masterB_reset_reset_bridge_in_reset_reset), //       clk_reset.reset
		.m0_address              (st_alu_0_s0_agent_m0_address),                 //              m0.address
		.m0_burstcount           (st_alu_0_s0_agent_m0_burstcount),              //                .burstcount
		.m0_byteenable           (st_alu_0_s0_agent_m0_byteenable),              //                .byteenable
		.m0_debugaccess          (st_alu_0_s0_agent_m0_debugaccess),             //                .debugaccess
		.m0_lock                 (st_alu_0_s0_agent_m0_lock),                    //                .lock
		.m0_readdata             (st_alu_0_s0_agent_m0_readdata),                //                .readdata
		.m0_readdatavalid        (st_alu_0_s0_agent_m0_readdatavalid),           //                .readdatavalid
		.m0_read                 (st_alu_0_s0_agent_m0_read),                    //                .read
		.m0_waitrequest          (st_alu_0_s0_agent_m0_waitrequest),             //                .waitrequest
		.m0_writedata            (st_alu_0_s0_agent_m0_writedata),               //                .writedata
		.m0_write                (st_alu_0_s0_agent_m0_write),                   //                .write
		.rp_endofpacket          (st_alu_0_s0_agent_rp_endofpacket),             //              rp.endofpacket
		.rp_ready                (st_alu_0_s0_agent_rp_ready),                   //                .ready
		.rp_valid                (st_alu_0_s0_agent_rp_valid),                   //                .valid
		.rp_data                 (st_alu_0_s0_agent_rp_data),                    //                .data
		.rp_startofpacket        (st_alu_0_s0_agent_rp_startofpacket),           //                .startofpacket
		.cp_ready                (cmd_mux_src_ready),                            //              cp.ready
		.cp_valid                (cmd_mux_src_valid),                            //                .valid
		.cp_data                 (cmd_mux_src_data),                             //                .data
		.cp_startofpacket        (cmd_mux_src_startofpacket),                    //                .startofpacket
		.cp_endofpacket          (cmd_mux_src_endofpacket),                      //                .endofpacket
		.cp_channel              (cmd_mux_src_channel),                          //                .channel
		.rf_sink_ready           (st_alu_0_s0_agent_rsp_fifo_out_ready),         //         rf_sink.ready
		.rf_sink_valid           (st_alu_0_s0_agent_rsp_fifo_out_valid),         //                .valid
		.rf_sink_startofpacket   (st_alu_0_s0_agent_rsp_fifo_out_startofpacket), //                .startofpacket
		.rf_sink_endofpacket     (st_alu_0_s0_agent_rsp_fifo_out_endofpacket),   //                .endofpacket
		.rf_sink_data            (st_alu_0_s0_agent_rsp_fifo_out_data),          //                .data
		.rf_source_ready         (st_alu_0_s0_agent_rf_source_ready),            //       rf_source.ready
		.rf_source_valid         (st_alu_0_s0_agent_rf_source_valid),            //                .valid
		.rf_source_startofpacket (st_alu_0_s0_agent_rf_source_startofpacket),    //                .startofpacket
		.rf_source_endofpacket   (st_alu_0_s0_agent_rf_source_endofpacket),      //                .endofpacket
		.rf_source_data          (st_alu_0_s0_agent_rf_source_data),             //                .data
		.rdata_fifo_sink_ready   (avalon_st_adapter_out_0_ready),                // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (avalon_st_adapter_out_0_valid),                //                .valid
		.rdata_fifo_sink_data    (avalon_st_adapter_out_0_data),                 //                .data
		.rdata_fifo_sink_error   (avalon_st_adapter_out_0_error),                //                .error
		.rdata_fifo_src_ready    (st_alu_0_s0_agent_rdata_fifo_src_ready),       //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (st_alu_0_s0_agent_rdata_fifo_src_valid),       //                .valid
		.rdata_fifo_src_data     (st_alu_0_s0_agent_rdata_fifo_src_data),        //                .data
		.m0_response             (2'b00),                                        //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                          //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (103),
		.FIFO_DEPTH          (2),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) st_alu_0_s0_agent_rsp_fifo (
		.clk               (clk_0_clk_clk),                                //       clk.clk
		.reset             (my_masterB_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_data           (st_alu_0_s0_agent_rf_source_data),             //        in.data
		.in_valid          (st_alu_0_s0_agent_rf_source_valid),            //          .valid
		.in_ready          (st_alu_0_s0_agent_rf_source_ready),            //          .ready
		.in_startofpacket  (st_alu_0_s0_agent_rf_source_startofpacket),    //          .startofpacket
		.in_endofpacket    (st_alu_0_s0_agent_rf_source_endofpacket),      //          .endofpacket
		.out_data          (st_alu_0_s0_agent_rsp_fifo_out_data),          //       out.data
		.out_valid         (st_alu_0_s0_agent_rsp_fifo_out_valid),         //          .valid
		.out_ready         (st_alu_0_s0_agent_rsp_fifo_out_ready),         //          .ready
		.out_startofpacket (st_alu_0_s0_agent_rsp_fifo_out_startofpacket), //          .startofpacket
		.out_endofpacket   (st_alu_0_s0_agent_rsp_fifo_out_endofpacket),   //          .endofpacket
		.csr_address       (2'b00),                                        // (terminated)
		.csr_read          (1'b0),                                         // (terminated)
		.csr_write         (1'b0),                                         // (terminated)
		.csr_readdata      (),                                             // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),         // (terminated)
		.almost_full_data  (),                                             // (terminated)
		.almost_empty_data (),                                             // (terminated)
		.in_empty          (1'b0),                                         // (terminated)
		.out_empty         (),                                             // (terminated)
		.in_error          (1'b0),                                         // (terminated)
		.out_error         (),                                             // (terminated)
		.in_channel        (1'b0),                                         // (terminated)
		.out_channel       ()                                              // (terminated)
	);

	altera_merlin_slave_agent #(
		.PKT_ORI_BURST_SIZE_H      (101),
		.PKT_ORI_BURST_SIZE_L      (99),
		.PKT_RESPONSE_STATUS_H     (98),
		.PKT_RESPONSE_STATUS_L     (97),
		.PKT_BURST_SIZE_H          (80),
		.PKT_BURST_SIZE_L          (78),
		.PKT_TRANS_LOCK            (72),
		.PKT_BEGIN_BURST           (85),
		.PKT_PROTECTION_H          (92),
		.PKT_PROTECTION_L          (90),
		.PKT_BURSTWRAP_H           (77),
		.PKT_BURSTWRAP_L           (77),
		.PKT_BYTE_CNT_H            (76),
		.PKT_BYTE_CNT_L            (74),
		.PKT_ADDR_H                (67),
		.PKT_ADDR_L                (36),
		.PKT_TRANS_COMPRESSED_READ (68),
		.PKT_TRANS_POSTED          (69),
		.PKT_TRANS_WRITE           (70),
		.PKT_TRANS_READ            (71),
		.PKT_DATA_H                (31),
		.PKT_DATA_L                (0),
		.PKT_BYTEEN_H              (35),
		.PKT_BYTEEN_L              (32),
		.PKT_SRC_ID_H              (87),
		.PKT_SRC_ID_L              (87),
		.PKT_DEST_ID_H             (88),
		.PKT_DEST_ID_L             (88),
		.PKT_SYMBOL_W              (8),
		.ST_CHANNEL_W              (2),
		.ST_DATA_W                 (102),
		.AVS_BURSTCOUNT_W          (3),
		.SUPPRESS_0_BYTEEN_CMD     (0),
		.PREVENT_FIFO_OVERFLOW     (1),
		.USE_READRESPONSE          (0),
		.USE_WRITERESPONSE         (0),
		.ECC_ENABLE                (0)
	) st_alu_1_s0_agent (
		.clk                     (clk_0_clk_clk),                                //             clk.clk
		.reset                   (my_masterB_reset_reset_bridge_in_reset_reset), //       clk_reset.reset
		.m0_address              (st_alu_1_s0_agent_m0_address),                 //              m0.address
		.m0_burstcount           (st_alu_1_s0_agent_m0_burstcount),              //                .burstcount
		.m0_byteenable           (st_alu_1_s0_agent_m0_byteenable),              //                .byteenable
		.m0_debugaccess          (st_alu_1_s0_agent_m0_debugaccess),             //                .debugaccess
		.m0_lock                 (st_alu_1_s0_agent_m0_lock),                    //                .lock
		.m0_readdata             (st_alu_1_s0_agent_m0_readdata),                //                .readdata
		.m0_readdatavalid        (st_alu_1_s0_agent_m0_readdatavalid),           //                .readdatavalid
		.m0_read                 (st_alu_1_s0_agent_m0_read),                    //                .read
		.m0_waitrequest          (st_alu_1_s0_agent_m0_waitrequest),             //                .waitrequest
		.m0_writedata            (st_alu_1_s0_agent_m0_writedata),               //                .writedata
		.m0_write                (st_alu_1_s0_agent_m0_write),                   //                .write
		.rp_endofpacket          (st_alu_1_s0_agent_rp_endofpacket),             //              rp.endofpacket
		.rp_ready                (st_alu_1_s0_agent_rp_ready),                   //                .ready
		.rp_valid                (st_alu_1_s0_agent_rp_valid),                   //                .valid
		.rp_data                 (st_alu_1_s0_agent_rp_data),                    //                .data
		.rp_startofpacket        (st_alu_1_s0_agent_rp_startofpacket),           //                .startofpacket
		.cp_ready                (cmd_mux_001_src_ready),                        //              cp.ready
		.cp_valid                (cmd_mux_001_src_valid),                        //                .valid
		.cp_data                 (cmd_mux_001_src_data),                         //                .data
		.cp_startofpacket        (cmd_mux_001_src_startofpacket),                //                .startofpacket
		.cp_endofpacket          (cmd_mux_001_src_endofpacket),                  //                .endofpacket
		.cp_channel              (cmd_mux_001_src_channel),                      //                .channel
		.rf_sink_ready           (st_alu_1_s0_agent_rsp_fifo_out_ready),         //         rf_sink.ready
		.rf_sink_valid           (st_alu_1_s0_agent_rsp_fifo_out_valid),         //                .valid
		.rf_sink_startofpacket   (st_alu_1_s0_agent_rsp_fifo_out_startofpacket), //                .startofpacket
		.rf_sink_endofpacket     (st_alu_1_s0_agent_rsp_fifo_out_endofpacket),   //                .endofpacket
		.rf_sink_data            (st_alu_1_s0_agent_rsp_fifo_out_data),          //                .data
		.rf_source_ready         (st_alu_1_s0_agent_rf_source_ready),            //       rf_source.ready
		.rf_source_valid         (st_alu_1_s0_agent_rf_source_valid),            //                .valid
		.rf_source_startofpacket (st_alu_1_s0_agent_rf_source_startofpacket),    //                .startofpacket
		.rf_source_endofpacket   (st_alu_1_s0_agent_rf_source_endofpacket),      //                .endofpacket
		.rf_source_data          (st_alu_1_s0_agent_rf_source_data),             //                .data
		.rdata_fifo_sink_ready   (avalon_st_adapter_001_out_0_ready),            // rdata_fifo_sink.ready
		.rdata_fifo_sink_valid   (avalon_st_adapter_001_out_0_valid),            //                .valid
		.rdata_fifo_sink_data    (avalon_st_adapter_001_out_0_data),             //                .data
		.rdata_fifo_sink_error   (avalon_st_adapter_001_out_0_error),            //                .error
		.rdata_fifo_src_ready    (st_alu_1_s0_agent_rdata_fifo_src_ready),       //  rdata_fifo_src.ready
		.rdata_fifo_src_valid    (st_alu_1_s0_agent_rdata_fifo_src_valid),       //                .valid
		.rdata_fifo_src_data     (st_alu_1_s0_agent_rdata_fifo_src_data),        //                .data
		.m0_response             (2'b00),                                        //     (terminated)
		.m0_writeresponsevalid   (1'b0)                                          //     (terminated)
	);

	altera_avalon_sc_fifo #(
		.SYMBOLS_PER_BEAT    (1),
		.BITS_PER_SYMBOL     (103),
		.FIFO_DEPTH          (2),
		.CHANNEL_WIDTH       (0),
		.ERROR_WIDTH         (0),
		.USE_PACKETS         (1),
		.USE_FILL_LEVEL      (0),
		.EMPTY_LATENCY       (1),
		.USE_MEMORY_BLOCKS   (0),
		.USE_STORE_FORWARD   (0),
		.USE_ALMOST_FULL_IF  (0),
		.USE_ALMOST_EMPTY_IF (0)
	) st_alu_1_s0_agent_rsp_fifo (
		.clk               (clk_0_clk_clk),                                //       clk.clk
		.reset             (my_masterB_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.in_data           (st_alu_1_s0_agent_rf_source_data),             //        in.data
		.in_valid          (st_alu_1_s0_agent_rf_source_valid),            //          .valid
		.in_ready          (st_alu_1_s0_agent_rf_source_ready),            //          .ready
		.in_startofpacket  (st_alu_1_s0_agent_rf_source_startofpacket),    //          .startofpacket
		.in_endofpacket    (st_alu_1_s0_agent_rf_source_endofpacket),      //          .endofpacket
		.out_data          (st_alu_1_s0_agent_rsp_fifo_out_data),          //       out.data
		.out_valid         (st_alu_1_s0_agent_rsp_fifo_out_valid),         //          .valid
		.out_ready         (st_alu_1_s0_agent_rsp_fifo_out_ready),         //          .ready
		.out_startofpacket (st_alu_1_s0_agent_rsp_fifo_out_startofpacket), //          .startofpacket
		.out_endofpacket   (st_alu_1_s0_agent_rsp_fifo_out_endofpacket),   //          .endofpacket
		.csr_address       (2'b00),                                        // (terminated)
		.csr_read          (1'b0),                                         // (terminated)
		.csr_write         (1'b0),                                         // (terminated)
		.csr_readdata      (),                                             // (terminated)
		.csr_writedata     (32'b00000000000000000000000000000000),         // (terminated)
		.almost_full_data  (),                                             // (terminated)
		.almost_empty_data (),                                             // (terminated)
		.in_empty          (1'b0),                                         // (terminated)
		.out_empty         (),                                             // (terminated)
		.in_error          (1'b0),                                         // (terminated)
		.out_error         (),                                             // (terminated)
		.in_channel        (1'b0),                                         // (terminated)
		.out_channel       ()                                              // (terminated)
	);

	Lab1_sys_mm_interconnect_1_router router (
		.sink_ready         (my_masterb_m0_agent_cp_ready),                 //      sink.ready
		.sink_valid         (my_masterb_m0_agent_cp_valid),                 //          .valid
		.sink_data          (my_masterb_m0_agent_cp_data),                  //          .data
		.sink_startofpacket (my_masterb_m0_agent_cp_startofpacket),         //          .startofpacket
		.sink_endofpacket   (my_masterb_m0_agent_cp_endofpacket),           //          .endofpacket
		.clk                (clk_0_clk_clk),                                //       clk.clk
		.reset              (my_masterB_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_src_ready),                             //       src.ready
		.src_valid          (router_src_valid),                             //          .valid
		.src_data           (router_src_data),                              //          .data
		.src_channel        (router_src_channel),                           //          .channel
		.src_startofpacket  (router_src_startofpacket),                     //          .startofpacket
		.src_endofpacket    (router_src_endofpacket)                        //          .endofpacket
	);

	Lab1_sys_mm_interconnect_1_router_001 router_001 (
		.sink_ready         (st_alu_0_s0_agent_rp_ready),                   //      sink.ready
		.sink_valid         (st_alu_0_s0_agent_rp_valid),                   //          .valid
		.sink_data          (st_alu_0_s0_agent_rp_data),                    //          .data
		.sink_startofpacket (st_alu_0_s0_agent_rp_startofpacket),           //          .startofpacket
		.sink_endofpacket   (st_alu_0_s0_agent_rp_endofpacket),             //          .endofpacket
		.clk                (clk_0_clk_clk),                                //       clk.clk
		.reset              (my_masterB_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_001_src_ready),                         //       src.ready
		.src_valid          (router_001_src_valid),                         //          .valid
		.src_data           (router_001_src_data),                          //          .data
		.src_channel        (router_001_src_channel),                       //          .channel
		.src_startofpacket  (router_001_src_startofpacket),                 //          .startofpacket
		.src_endofpacket    (router_001_src_endofpacket)                    //          .endofpacket
	);

	Lab1_sys_mm_interconnect_1_router_001 router_002 (
		.sink_ready         (st_alu_1_s0_agent_rp_ready),                   //      sink.ready
		.sink_valid         (st_alu_1_s0_agent_rp_valid),                   //          .valid
		.sink_data          (st_alu_1_s0_agent_rp_data),                    //          .data
		.sink_startofpacket (st_alu_1_s0_agent_rp_startofpacket),           //          .startofpacket
		.sink_endofpacket   (st_alu_1_s0_agent_rp_endofpacket),             //          .endofpacket
		.clk                (clk_0_clk_clk),                                //       clk.clk
		.reset              (my_masterB_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready          (router_002_src_ready),                         //       src.ready
		.src_valid          (router_002_src_valid),                         //          .valid
		.src_data           (router_002_src_data),                          //          .data
		.src_channel        (router_002_src_channel),                       //          .channel
		.src_startofpacket  (router_002_src_startofpacket),                 //          .startofpacket
		.src_endofpacket    (router_002_src_endofpacket)                    //          .endofpacket
	);

	Lab1_sys_mm_interconnect_1_cmd_demux cmd_demux (
		.clk                (clk_0_clk_clk),                                //       clk.clk
		.reset              (my_masterB_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_src_ready),                             //      sink.ready
		.sink_channel       (router_src_channel),                           //          .channel
		.sink_data          (router_src_data),                              //          .data
		.sink_startofpacket (router_src_startofpacket),                     //          .startofpacket
		.sink_endofpacket   (router_src_endofpacket),                       //          .endofpacket
		.sink_valid         (router_src_valid),                             //          .valid
		.src0_ready         (cmd_demux_src0_ready),                         //      src0.ready
		.src0_valid         (cmd_demux_src0_valid),                         //          .valid
		.src0_data          (cmd_demux_src0_data),                          //          .data
		.src0_channel       (cmd_demux_src0_channel),                       //          .channel
		.src0_startofpacket (cmd_demux_src0_startofpacket),                 //          .startofpacket
		.src0_endofpacket   (cmd_demux_src0_endofpacket),                   //          .endofpacket
		.src1_ready         (cmd_demux_src1_ready),                         //      src1.ready
		.src1_valid         (cmd_demux_src1_valid),                         //          .valid
		.src1_data          (cmd_demux_src1_data),                          //          .data
		.src1_channel       (cmd_demux_src1_channel),                       //          .channel
		.src1_startofpacket (cmd_demux_src1_startofpacket),                 //          .startofpacket
		.src1_endofpacket   (cmd_demux_src1_endofpacket)                    //          .endofpacket
	);

	Lab1_sys_mm_interconnect_1_cmd_mux cmd_mux (
		.clk                 (clk_0_clk_clk),                                //       clk.clk
		.reset               (my_masterB_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_src_ready),                            //       src.ready
		.src_valid           (cmd_mux_src_valid),                            //          .valid
		.src_data            (cmd_mux_src_data),                             //          .data
		.src_channel         (cmd_mux_src_channel),                          //          .channel
		.src_startofpacket   (cmd_mux_src_startofpacket),                    //          .startofpacket
		.src_endofpacket     (cmd_mux_src_endofpacket),                      //          .endofpacket
		.sink0_ready         (cmd_demux_src0_ready),                         //     sink0.ready
		.sink0_valid         (cmd_demux_src0_valid),                         //          .valid
		.sink0_channel       (cmd_demux_src0_channel),                       //          .channel
		.sink0_data          (cmd_demux_src0_data),                          //          .data
		.sink0_startofpacket (cmd_demux_src0_startofpacket),                 //          .startofpacket
		.sink0_endofpacket   (cmd_demux_src0_endofpacket)                    //          .endofpacket
	);

	Lab1_sys_mm_interconnect_1_cmd_mux cmd_mux_001 (
		.clk                 (clk_0_clk_clk),                                //       clk.clk
		.reset               (my_masterB_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (cmd_mux_001_src_ready),                        //       src.ready
		.src_valid           (cmd_mux_001_src_valid),                        //          .valid
		.src_data            (cmd_mux_001_src_data),                         //          .data
		.src_channel         (cmd_mux_001_src_channel),                      //          .channel
		.src_startofpacket   (cmd_mux_001_src_startofpacket),                //          .startofpacket
		.src_endofpacket     (cmd_mux_001_src_endofpacket),                  //          .endofpacket
		.sink0_ready         (cmd_demux_src1_ready),                         //     sink0.ready
		.sink0_valid         (cmd_demux_src1_valid),                         //          .valid
		.sink0_channel       (cmd_demux_src1_channel),                       //          .channel
		.sink0_data          (cmd_demux_src1_data),                          //          .data
		.sink0_startofpacket (cmd_demux_src1_startofpacket),                 //          .startofpacket
		.sink0_endofpacket   (cmd_demux_src1_endofpacket)                    //          .endofpacket
	);

	Lab1_sys_mm_interconnect_1_rsp_demux rsp_demux (
		.clk                (clk_0_clk_clk),                                //       clk.clk
		.reset              (my_masterB_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_001_src_ready),                         //      sink.ready
		.sink_channel       (router_001_src_channel),                       //          .channel
		.sink_data          (router_001_src_data),                          //          .data
		.sink_startofpacket (router_001_src_startofpacket),                 //          .startofpacket
		.sink_endofpacket   (router_001_src_endofpacket),                   //          .endofpacket
		.sink_valid         (router_001_src_valid),                         //          .valid
		.src0_ready         (rsp_demux_src0_ready),                         //      src0.ready
		.src0_valid         (rsp_demux_src0_valid),                         //          .valid
		.src0_data          (rsp_demux_src0_data),                          //          .data
		.src0_channel       (rsp_demux_src0_channel),                       //          .channel
		.src0_startofpacket (rsp_demux_src0_startofpacket),                 //          .startofpacket
		.src0_endofpacket   (rsp_demux_src0_endofpacket)                    //          .endofpacket
	);

	Lab1_sys_mm_interconnect_1_rsp_demux rsp_demux_001 (
		.clk                (clk_0_clk_clk),                                //       clk.clk
		.reset              (my_masterB_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.sink_ready         (router_002_src_ready),                         //      sink.ready
		.sink_channel       (router_002_src_channel),                       //          .channel
		.sink_data          (router_002_src_data),                          //          .data
		.sink_startofpacket (router_002_src_startofpacket),                 //          .startofpacket
		.sink_endofpacket   (router_002_src_endofpacket),                   //          .endofpacket
		.sink_valid         (router_002_src_valid),                         //          .valid
		.src0_ready         (rsp_demux_001_src0_ready),                     //      src0.ready
		.src0_valid         (rsp_demux_001_src0_valid),                     //          .valid
		.src0_data          (rsp_demux_001_src0_data),                      //          .data
		.src0_channel       (rsp_demux_001_src0_channel),                   //          .channel
		.src0_startofpacket (rsp_demux_001_src0_startofpacket),             //          .startofpacket
		.src0_endofpacket   (rsp_demux_001_src0_endofpacket)                //          .endofpacket
	);

	Lab1_sys_mm_interconnect_1_rsp_mux rsp_mux (
		.clk                 (clk_0_clk_clk),                                //       clk.clk
		.reset               (my_masterB_reset_reset_bridge_in_reset_reset), // clk_reset.reset
		.src_ready           (rsp_mux_src_ready),                            //       src.ready
		.src_valid           (rsp_mux_src_valid),                            //          .valid
		.src_data            (rsp_mux_src_data),                             //          .data
		.src_channel         (rsp_mux_src_channel),                          //          .channel
		.src_startofpacket   (rsp_mux_src_startofpacket),                    //          .startofpacket
		.src_endofpacket     (rsp_mux_src_endofpacket),                      //          .endofpacket
		.sink0_ready         (rsp_demux_src0_ready),                         //     sink0.ready
		.sink0_valid         (rsp_demux_src0_valid),                         //          .valid
		.sink0_channel       (rsp_demux_src0_channel),                       //          .channel
		.sink0_data          (rsp_demux_src0_data),                          //          .data
		.sink0_startofpacket (rsp_demux_src0_startofpacket),                 //          .startofpacket
		.sink0_endofpacket   (rsp_demux_src0_endofpacket),                   //          .endofpacket
		.sink1_ready         (rsp_demux_001_src0_ready),                     //     sink1.ready
		.sink1_valid         (rsp_demux_001_src0_valid),                     //          .valid
		.sink1_channel       (rsp_demux_001_src0_channel),                   //          .channel
		.sink1_data          (rsp_demux_001_src0_data),                      //          .data
		.sink1_startofpacket (rsp_demux_001_src0_startofpacket),             //          .startofpacket
		.sink1_endofpacket   (rsp_demux_001_src0_endofpacket)                //          .endofpacket
	);

	Lab1_sys_mm_interconnect_1_avalon_st_adapter #(
		.inBitsPerSymbol (34),
		.inUsePackets    (0),
		.inDataWidth     (34),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (34),
		.outChannelWidth (0),
		.outErrorWidth   (1),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter (
		.in_clk_0_clk   (clk_0_clk_clk),                                // in_clk_0.clk
		.in_rst_0_reset (my_masterB_reset_reset_bridge_in_reset_reset), // in_rst_0.reset
		.in_0_data      (st_alu_0_s0_agent_rdata_fifo_src_data),        //     in_0.data
		.in_0_valid     (st_alu_0_s0_agent_rdata_fifo_src_valid),       //         .valid
		.in_0_ready     (st_alu_0_s0_agent_rdata_fifo_src_ready),       //         .ready
		.out_0_data     (avalon_st_adapter_out_0_data),                 //    out_0.data
		.out_0_valid    (avalon_st_adapter_out_0_valid),                //         .valid
		.out_0_ready    (avalon_st_adapter_out_0_ready),                //         .ready
		.out_0_error    (avalon_st_adapter_out_0_error)                 //         .error
	);

	Lab1_sys_mm_interconnect_1_avalon_st_adapter #(
		.inBitsPerSymbol (34),
		.inUsePackets    (0),
		.inDataWidth     (34),
		.inChannelWidth  (0),
		.inErrorWidth    (0),
		.inUseEmptyPort  (0),
		.inUseValid      (1),
		.inUseReady      (1),
		.inReadyLatency  (0),
		.outDataWidth    (34),
		.outChannelWidth (0),
		.outErrorWidth   (1),
		.outUseEmptyPort (0),
		.outUseValid     (1),
		.outUseReady     (1),
		.outReadyLatency (0)
	) avalon_st_adapter_001 (
		.in_clk_0_clk   (clk_0_clk_clk),                                // in_clk_0.clk
		.in_rst_0_reset (my_masterB_reset_reset_bridge_in_reset_reset), // in_rst_0.reset
		.in_0_data      (st_alu_1_s0_agent_rdata_fifo_src_data),        //     in_0.data
		.in_0_valid     (st_alu_1_s0_agent_rdata_fifo_src_valid),       //         .valid
		.in_0_ready     (st_alu_1_s0_agent_rdata_fifo_src_ready),       //         .ready
		.out_0_data     (avalon_st_adapter_001_out_0_data),             //    out_0.data
		.out_0_valid    (avalon_st_adapter_001_out_0_valid),            //         .valid
		.out_0_ready    (avalon_st_adapter_001_out_0_ready),            //         .ready
		.out_0_error    (avalon_st_adapter_001_out_0_error)             //         .error
	);

endmodule
