# TCL File Generated by Component Editor 20.1
# Fri Apr 16 10:00:02 GMT+03:00 2021
# DO NOT MODIFY


# 
# my_masterB "my_masterB_component" v1.0
#  2021.04.16.10:00:02
# 
# 

# 
# request TCL package from ACDS 16.1
# 
package require -exact qsys 16.1


# 
# module my_masterB
# 
set_module_property DESCRIPTION ""
set_module_property NAME my_masterB
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property GROUP Training
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME my_masterB_component
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL my_masterB
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file my_masterB.sv SYSTEM_VERILOG PATH my_masterB.sv TOP_LEVEL_FILE

add_fileset SIM_VERILOG SIM_VERILOG "" ""
set_fileset_property SIM_VERILOG TOP_LEVEL my_masterB
set_fileset_property SIM_VERILOG ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property SIM_VERILOG ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file my_masterB.sv SYSTEM_VERILOG PATH my_masterB.sv


# 
# parameters
# 
add_parameter address_1 NATURAL 0 ""
set_parameter_property address_1 DEFAULT_VALUE 0
set_parameter_property address_1 DISPLAY_NAME address_1
set_parameter_property address_1 WIDTH ""
set_parameter_property address_1 TYPE NATURAL
set_parameter_property address_1 UNITS None
set_parameter_property address_1 ALLOWED_RANGES 0:2147483647
set_parameter_property address_1 DESCRIPTION ""
set_parameter_property address_1 HDL_PARAMETER true
add_parameter data_1 NATURAL 111 ""
set_parameter_property data_1 DEFAULT_VALUE 111
set_parameter_property data_1 DISPLAY_NAME data_1
set_parameter_property data_1 WIDTH ""
set_parameter_property data_1 TYPE NATURAL
set_parameter_property data_1 UNITS None
set_parameter_property data_1 ALLOWED_RANGES 0:2147483647
set_parameter_property data_1 DESCRIPTION ""
set_parameter_property data_1 HDL_PARAMETER true
add_parameter address_2 NATURAL 1 ""
set_parameter_property address_2 DEFAULT_VALUE 1
set_parameter_property address_2 DISPLAY_NAME address_2
set_parameter_property address_2 WIDTH ""
set_parameter_property address_2 TYPE NATURAL
set_parameter_property address_2 UNITS None
set_parameter_property address_2 ALLOWED_RANGES 0:2147483647
set_parameter_property address_2 DESCRIPTION ""
set_parameter_property address_2 HDL_PARAMETER true
add_parameter data_2 NATURAL 333 ""
set_parameter_property data_2 DEFAULT_VALUE 333
set_parameter_property data_2 DISPLAY_NAME data_2
set_parameter_property data_2 WIDTH ""
set_parameter_property data_2 TYPE NATURAL
set_parameter_property data_2 UNITS None
set_parameter_property data_2 ALLOWED_RANGES 0:2147483647
set_parameter_property data_2 DESCRIPTION ""
set_parameter_property data_2 HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock csi_clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset rsi_reset reset Input 1


# 
# connection point m0
# 
add_interface m0 avalon start
set_interface_property m0 addressUnits SYMBOLS
set_interface_property m0 associatedClock clock
set_interface_property m0 associatedReset reset
set_interface_property m0 bitsPerSymbol 8
set_interface_property m0 burstOnBurstBoundariesOnly false
set_interface_property m0 burstcountUnits WORDS
set_interface_property m0 doStreamReads false
set_interface_property m0 doStreamWrites false
set_interface_property m0 holdTime 0
set_interface_property m0 linewrapBursts false
set_interface_property m0 maximumPendingReadTransactions 0
set_interface_property m0 maximumPendingWriteTransactions 0
set_interface_property m0 readLatency 0
set_interface_property m0 readWaitTime 1
set_interface_property m0 setupTime 0
set_interface_property m0 timingUnits Cycles
set_interface_property m0 writeWaitTime 0
set_interface_property m0 ENABLED true
set_interface_property m0 EXPORT_OF ""
set_interface_property m0 PORT_NAME_MAP ""
set_interface_property m0 CMSIS_SVD_VARIABLES ""
set_interface_property m0 SVD_ADDRESS_GROUP ""

add_interface_port m0 avm_m0_address address Output 32
add_interface_port m0 avm_m0_write write Output 1
add_interface_port m0 avm_m0_writedata writedata Output 32
add_interface_port m0 avm_m0_waitrequest waitrequest Input 1

